version: "3"

volumes:
  config:

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: m7salam/smicolon-lex-office-invoice-uploader:latest
    container_name: lexoffice_invoice_upload
    volumes:
      - ./config:/app/config
    environment:
      TZ: Europe/Berlin
      CRON: '*/5 * * * *'
    restart: unless-stopped
